#ifndef INCLUDE_RESTCLIENT_CPP_VERSION_H_
#define INCLUDE_RESTCLIENT_CPP_VERSION_H_
// this file is not automatically generated by meson, so we need to update it manually
#define RESTCLIENT_VERSION "0.5.2"
#endif  // INCLUDE_RESTCLIENT_CPP_VERSION_H_
